// <auto-generated />
using System;
using Alojamiento.DataManagement.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Alojamiento.DataManagement.Migrations
{
    [DbContext(typeof(AlojamientoDbContext))]
    [Migration("20260427221717_RestructuringFullSchema")]
    partial class RestructuringFullSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.DisponibilidadHabitacion", b =>
                {
                    b.Property<int>("DisponibilidadHabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisponibilidadHabitacionId"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("integer");

                    b.HasKey("DisponibilidadHabitacionId");

                    b.HasIndex("HabitacionId");

                    b.ToTable("DisponibilidadHabitacion", "alo");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.Habitacion", b =>
                {
                    b.Property<int>("HabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HabitacionId"));

                    b.Property<bool>("AdmiteMascotas")
                        .HasColumnType("boolean");

                    b.Property<int>("CapacidadAdultos")
                        .HasColumnType("integer");

                    b.Property<int>("CapacidadNinos")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumBanos")
                        .HasColumnType("integer");

                    b.Property<int>("NumDormitorios")
                        .HasColumnType("integer");

                    b.Property<int>("PropiedadId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SuperficieM2")
                        .HasColumnType("numeric");

                    b.Property<bool>("TieneAireAcondicionado")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneCocina")
                        .HasColumnType("boolean");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("HabitacionId");

                    b.HasIndex("PropiedadId");

                    b.ToTable("Habitacion", "alo");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.HabitacionFoto", b =>
                {
                    b.Property<int>("HabitacionFotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HabitacionFotoId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HabitacionFotoId");

                    b.HasIndex("HabitacionId");

                    b.ToTable("HabitacionFoto", "alo");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.Propiedad", b =>
                {
                    b.Property<int>("PropiedadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PropiedadId"));

                    b.Property<bool>("AdmiteMascotas")
                        .HasColumnType("boolean");

                    b.Property<int>("AnfitrionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CalificacionPromedio")
                        .HasColumnType("numeric");

                    b.Property<int>("CiudadId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoPropiedad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Estrellas")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("numeric");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoAlojamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalResenas")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.Property<bool>("Verificada")
                        .HasColumnType("boolean");

                    b.HasKey("PropiedadId");

                    b.HasIndex("AnfitrionId");

                    b.HasIndex("CiudadId");

                    b.HasIndex("TipoAlojamientoId");

                    b.ToTable("Propiedad", "alo");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.PropiedadFoto", b =>
                {
                    b.Property<int>("PropiedadFotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PropiedadFotoId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("PropiedadId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.HasKey("PropiedadFotoId");

                    b.HasIndex("PropiedadId");

                    b.ToTable("PropiedadFoto", "alo");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.PropiedadPolitica", b =>
                {
                    b.Property<int>("PropiedadPoliticaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PropiedadPoliticaId"));

                    b.Property<int?>("EdadMinimaReserva")
                        .HasColumnType("integer");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HoraCheckIn")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraCheckOut")
                        .HasColumnType("interval");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<bool>("PermiteMascotas")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermiteNinos")
                        .HasColumnType("boolean");

                    b.Property<string>("PoliticaCancelacion")
                        .HasColumnType("text");

                    b.Property<int>("PropiedadId")
                        .HasColumnType("integer");

                    b.Property<string>("ReglasCasa")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("PropiedadPoliticaId");

                    b.HasIndex("PropiedadId")
                        .IsUnique();

                    b.ToTable("PropiedadPolitica", "alo");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.PropiedadServicio", b =>
                {
                    b.Property<int>("PropiedadId")
                        .HasColumnType("integer");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PropiedadServicioId")
                        .HasColumnType("integer");

                    b.HasKey("PropiedadId", "ServicioId");

                    b.HasIndex("ServicioId");

                    b.ToTable("PropiedadServicio", "alo");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.Servicio", b =>
                {
                    b.Property<int>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServicioId"));

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icono")
                        .HasColumnType("text");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("ServicioId");

                    b.ToTable("Servicio", "alo");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.TarifaHabitacion", b =>
                {
                    b.Property<int>("TarifaHabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TarifaHabitacionId"));

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("integer");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<int>("MonedaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasColumnType("numeric");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("TarifaHabitacionId");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("MonedaId");

                    b.ToTable("TarifaHabitacion", "alo");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.TipoAlojamiento", b =>
                {
                    b.Property<int>("TipoAlojamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoAlojamientoId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("TipoAlojamientoId");

                    b.ToTable("TipoAlojamiento", "alo");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Auditoria.AccesoUsuario", b =>
                {
                    b.Property<long>("AccesoUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AccesoUsuarioId"));

                    b.Property<bool>("Exitoso")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("AccesoUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AccesoUsuario", "aud");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Auditoria.AuditoriaGeneral", b =>
                {
                    b.Property<long>("AuditoriaGeneralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditoriaGeneralId"));

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("text");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("NombreEsquema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreTabla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistroId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioAccion")
                        .HasColumnType("text");

                    b.HasKey("AuditoriaGeneralId");

                    b.ToTable("AuditoriaGeneral", "aud");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Auditoria.ErrorAplicacion", b =>
                {
                    b.Property<long>("ErrorAplicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ErrorAplicacionId"));

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaError")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modulo")
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("ErrorAplicacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ErrorAplicacion", "aud");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Geografico.Ciudad", b =>
                {
                    b.Property<int>("CiudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CiudadId"));

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsCapital")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaisId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("CiudadId");

                    b.HasIndex("PaisId");

                    b.ToTable("Ciudad", "geo");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Geografico.Moneda", b =>
                {
                    b.Property<int>("MonedaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MonedaId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("MonedaId");

                    b.ToTable("Moneda", "geo");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Geografico.Pais", b =>
                {
                    b.Property<int>("PaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaisId"));

                    b.Property<string>("CodigoISO2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoISO3")
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("PaisId");

                    b.ToTable("Pais", "geo");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Geografico.PaisMoneda", b =>
                {
                    b.Property<int>("PaisId")
                        .HasColumnType("integer");

                    b.Property<int>("MonedaId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaisMonedaId")
                        .HasColumnType("integer");

                    b.HasKey("PaisId", "MonedaId");

                    b.HasIndex("MonedaId");

                    b.ToTable("PaisMoneda", "geo");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Geografico.TasaCambio", b =>
                {
                    b.Property<int>("TasaCambioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TasaCambioId"));

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVigencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<int>("MonedaDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("MonedaOrigenId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("numeric");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("TasaCambioId");

                    b.HasIndex("MonedaDestinoId");

                    b.HasIndex("MonedaOrigenId");

                    b.ToTable("TasaCambio", "geo");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Pagos.Factura", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FacturaId"));

                    b.Property<string>("DireccionFacturacion")
                        .HasColumnType("text");

                    b.Property<string>("DocumentoFacturacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoFactura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("numeric");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("NombreFacturacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PagoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("FacturaId");

                    b.HasIndex("PagoId")
                        .IsUnique();

                    b.ToTable("Factura", "pag");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Pagos.MetodoPagoCliente", b =>
                {
                    b.Property<int>("MetodoPagoClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MetodoPagoClienteId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FechaExpiracion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("MarcaTarjeta")
                        .HasColumnType("text");

                    b.Property<string>("NombreTitular")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UltimosCuatroDigitos")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("MetodoPagoClienteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("MetodoPagoCliente", "pag");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Pagos.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PagoId"));

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<int?>("MetodoPagoClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("MonedaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("ReferenciaPago")
                        .HasColumnType("text");

                    b.Property<int>("ReservaId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("PagoId");

                    b.HasIndex("MetodoPagoClienteId");

                    b.HasIndex("MonedaId");

                    b.HasIndex("ReservaId");

                    b.ToTable("Pago", "pag");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Pagos.PagoEstadoHistorial", b =>
                {
                    b.Property<long>("PagoEstadoHistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PagoEstadoHistorialId"));

                    b.Property<string>("EstadoAnterior")
                        .HasColumnType("text");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<int>("PagoId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioAccion")
                        .HasColumnType("text");

                    b.HasKey("PagoEstadoHistorialId");

                    b.HasIndex("PagoId");

                    b.ToTable("PagoEstadoHistorial", "pag");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.AdvertenciaCliente", b =>
                {
                    b.Property<int>("AdvertenciaClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdvertenciaClienteId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<int?>("ReservaId")
                        .HasColumnType("integer");

                    b.Property<int>("Severidad")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.HasKey("AdvertenciaClienteId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ReservaId");

                    b.ToTable("AdvertenciaCliente", "res");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.CancelacionReserva", b =>
                {
                    b.Property<int>("CancelacionReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CancelacionReservaId"));

                    b.Property<DateTime>("FechaCancelacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Penalizacion")
                        .HasColumnType("numeric");

                    b.Property<int>("ReservaId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioAccion")
                        .HasColumnType("text");

                    b.HasKey("CancelacionReservaId");

                    b.HasIndex("ReservaId")
                        .IsUnique();

                    b.ToTable("CancelacionReserva", "res");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.EncuestaExperiencia", b =>
                {
                    b.Property<int>("EncuestaExperienciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EncuestaExperienciaId"));

                    b.Property<decimal>("CalificacionGeneral")
                        .HasColumnType("numeric");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Comentarios")
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<decimal?>("Limpieza")
                        .HasColumnType("numeric");

                    b.Property<int>("PropiedadId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RelacionCalidadPrecio")
                        .HasColumnType("numeric");

                    b.Property<int>("ReservaId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Servicio")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ubicacion")
                        .HasColumnType("numeric");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.HasKey("EncuestaExperienciaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PropiedadId");

                    b.HasIndex("ReservaId")
                        .IsUnique();

                    b.ToTable("EncuestaExperiencia", "res");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.ResenaCliente", b =>
                {
                    b.Property<int>("ResenaClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResenaClienteId"));

                    b.Property<int>("AnfitrionId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsNoShow")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<decimal>("Puntuacion")
                        .HasColumnType("numeric");

                    b.Property<int>("ReservaId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.HasKey("ResenaClienteId");

                    b.HasIndex("AnfitrionId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ReservaId")
                        .IsUnique();

                    b.ToTable("ResenaCliente", "res");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.ResenaPropiedad", b =>
                {
                    b.Property<int>("ResenaPropiedadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResenaPropiedadId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<int>("PropiedadId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Puntuacion")
                        .HasColumnType("numeric");

                    b.Property<int>("ReservaId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.HasKey("ResenaPropiedadId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PropiedadId");

                    b.HasIndex("ReservaId")
                        .IsUnique();

                    b.ToTable("ResenaPropiedad", "res");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoReserva")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoReserva")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<bool>("LlevaMascotas")
                        .HasColumnType("boolean");

                    b.Property<int>("MonedaId")
                        .HasColumnType("integer");

                    b.Property<int>("NumAdultos")
                        .HasColumnType("integer");

                    b.Property<int>("NumHabitaciones")
                        .HasColumnType("integer");

                    b.Property<int>("NumNinos")
                        .HasColumnType("integer");

                    b.Property<int>("PropiedadId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("ReservaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MonedaId");

                    b.HasIndex("PropiedadId");

                    b.ToTable("Reserva", "res");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.ReservaEstadoHistorial", b =>
                {
                    b.Property<long>("ReservaEstadoHistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReservaEstadoHistorialId"));

                    b.Property<string>("EstadoAnterior")
                        .HasColumnType("text");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<int>("ReservaId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioAccion")
                        .HasColumnType("text");

                    b.HasKey("ReservaEstadoHistorialId");

                    b.HasIndex("ReservaId");

                    b.ToTable("ReservaEstadoHistorial", "res");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.ReservaHabitacionDetalle", b =>
                {
                    b.Property<int>("ReservaHabitacionDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservaHabitacionDetalleId"));

                    b.Property<int>("HabitacionId")
                        .HasColumnType("integer");

                    b.Property<int>("NumNoches")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasColumnType("numeric");

                    b.Property<int>("ReservaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubTotalHabitacion")
                        .HasColumnType("numeric");

                    b.HasKey("ReservaHabitacionDetalleId");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("ReservaId");

                    b.ToTable("ReservaHabitacionDetalle", "res");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Seguridad.Anfitrion", b =>
                {
                    b.Property<int>("AnfitrionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnfitrionId"));

                    b.Property<string>("CuentaBancaria")
                        .HasColumnType("text");

                    b.Property<string>("DocumentoFiscal")
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("NombreEmpresa")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.Property<bool>("Verificado")
                        .HasColumnType("boolean");

                    b.HasKey("AnfitrionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Anfitrion", "seg");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Seguridad.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<decimal>("Calificacion")
                        .HasColumnType("numeric");

                    b.Property<int?>("CiudadId")
                        .HasColumnType("integer");

                    b.Property<string>("Domicilio")
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<int>("TotalReservas")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("ClienteId");

                    b.HasIndex("CiudadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cliente", "seg");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Seguridad.Notificacion", b =>
                {
                    b.Property<long>("NotificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotificacionId"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("NotificacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificacion", "seg");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Seguridad.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("RolId");

                    b.ToTable("Rol", "seg");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Seguridad.TokenVerificacion", b =>
                {
                    b.Property<int>("TokenVerificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenVerificacionId"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("TokenVerificacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokenVerificacion", "seg");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Seguridad.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("EliminadoLogico")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario", "seg");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Seguridad.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioRolId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRol", "seg");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.DisponibilidadHabitacion", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Alojamientos.Habitacion", "Habitacion")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.Habitacion", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Alojamientos.Propiedad", "Propiedad")
                        .WithMany("Habitaciones")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.HabitacionFoto", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Alojamientos.Habitacion", "Habitacion")
                        .WithMany("Fotos")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.Propiedad", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Anfitrion", "Anfitrion")
                        .WithMany()
                        .HasForeignKey("AnfitrionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Geografico.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Alojamientos.TipoAlojamiento", "TipoAlojamiento")
                        .WithMany("Propiedades")
                        .HasForeignKey("TipoAlojamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anfitrion");

                    b.Navigation("Ciudad");

                    b.Navigation("TipoAlojamiento");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.PropiedadFoto", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Alojamientos.Propiedad", "Propiedad")
                        .WithMany("Fotos")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.PropiedadPolitica", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Alojamientos.Propiedad", "Propiedad")
                        .WithOne("Politica")
                        .HasForeignKey("Alojamiento.Domain.Entities.Alojamientos.PropiedadPolitica", "PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.PropiedadServicio", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Alojamientos.Propiedad", "Propiedad")
                        .WithMany("Servicios")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Alojamientos.Servicio", "Servicio")
                        .WithMany("PropiedadesServicios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propiedad");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.TarifaHabitacion", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Alojamientos.Habitacion", "Habitacion")
                        .WithMany("Tarifas")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Geografico.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Moneda");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Auditoria.AccesoUsuario", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Auditoria.ErrorAplicacion", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Geografico.Ciudad", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Geografico.Pais", "Pais")
                        .WithMany("Ciudades")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Geografico.PaisMoneda", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Geografico.Moneda", "Moneda")
                        .WithMany("PaisesMonedas")
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Geografico.Pais", "Pais")
                        .WithMany("PaisesMonedas")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moneda");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Geografico.TasaCambio", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Geografico.Moneda", "MonedaDestino")
                        .WithMany()
                        .HasForeignKey("MonedaDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Geografico.Moneda", "MonedaOrigen")
                        .WithMany()
                        .HasForeignKey("MonedaOrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonedaDestino");

                    b.Navigation("MonedaOrigen");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Pagos.Factura", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Pagos.Pago", "Pago")
                        .WithOne("Factura")
                        .HasForeignKey("Alojamiento.Domain.Entities.Pagos.Factura", "PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Pagos.MetodoPagoCliente", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Pagos.Pago", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Pagos.MetodoPagoCliente", "MetodoPagoCliente")
                        .WithMany("Pagos")
                        .HasForeignKey("MetodoPagoClienteId");

                    b.HasOne("Alojamiento.Domain.Entities.Geografico.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Reservas.Reserva", "Reserva")
                        .WithMany("Pagos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetodoPagoCliente");

                    b.Navigation("Moneda");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Pagos.PagoEstadoHistorial", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Pagos.Pago", "Pago")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.AdvertenciaCliente", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Reservas.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaId");

                    b.Navigation("Cliente");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.CancelacionReserva", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Reservas.Reserva", "Reserva")
                        .WithOne("Cancelacion")
                        .HasForeignKey("Alojamiento.Domain.Entities.Reservas.CancelacionReserva", "ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.EncuestaExperiencia", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Alojamientos.Propiedad", "Propiedad")
                        .WithMany()
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Reservas.Reserva", "Reserva")
                        .WithOne("Encuesta")
                        .HasForeignKey("Alojamiento.Domain.Entities.Reservas.EncuestaExperiencia", "ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Propiedad");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.ResenaCliente", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Anfitrion", "Anfitrion")
                        .WithMany()
                        .HasForeignKey("AnfitrionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Reservas.Reserva", "Reserva")
                        .WithOne("ResenaCliente")
                        .HasForeignKey("Alojamiento.Domain.Entities.Reservas.ResenaCliente", "ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anfitrion");

                    b.Navigation("Cliente");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.ResenaPropiedad", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Alojamientos.Propiedad", "Propiedad")
                        .WithMany()
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Reservas.Reserva", "Reserva")
                        .WithOne("ResenaPropiedad")
                        .HasForeignKey("Alojamiento.Domain.Entities.Reservas.ResenaPropiedad", "ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Propiedad");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.Reserva", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Geografico.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Alojamientos.Propiedad", "Propiedad")
                        .WithMany()
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Moneda");

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.ReservaEstadoHistorial", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Reservas.Reserva", "Reserva")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.ReservaHabitacionDetalle", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Alojamientos.Habitacion", "Habitacion")
                        .WithMany()
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Reservas.Reserva", "Reserva")
                        .WithMany("DetallesHabitacion")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Seguridad.Anfitrion", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Seguridad.Cliente", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Geografico.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId");

                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Seguridad.Notificacion", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Seguridad.TokenVerificacion", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Usuario", "Usuario")
                        .WithMany("Tokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Seguridad.UsuarioRol", b =>
                {
                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Rol", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alojamiento.Domain.Entities.Seguridad.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.Habitacion", b =>
                {
                    b.Navigation("Disponibilidades");

                    b.Navigation("Fotos");

                    b.Navigation("Tarifas");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.Propiedad", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Habitaciones");

                    b.Navigation("Politica");

                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.Servicio", b =>
                {
                    b.Navigation("PropiedadesServicios");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Alojamientos.TipoAlojamiento", b =>
                {
                    b.Navigation("Propiedades");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Geografico.Moneda", b =>
                {
                    b.Navigation("PaisesMonedas");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Geografico.Pais", b =>
                {
                    b.Navigation("Ciudades");

                    b.Navigation("PaisesMonedas");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Pagos.MetodoPagoCliente", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Pagos.Pago", b =>
                {
                    b.Navigation("Factura");

                    b.Navigation("HistorialEstados");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Reservas.Reserva", b =>
                {
                    b.Navigation("Cancelacion");

                    b.Navigation("DetallesHabitacion");

                    b.Navigation("Encuesta");

                    b.Navigation("HistorialEstados");

                    b.Navigation("Pagos");

                    b.Navigation("ResenaCliente");

                    b.Navigation("ResenaPropiedad");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Seguridad.Rol", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("Alojamiento.Domain.Entities.Seguridad.Usuario", b =>
                {
                    b.Navigation("Notificaciones");

                    b.Navigation("Tokens");

                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
